version: '3.8'

services:
  backend:
    build: ./web/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://warehouse_user:your_password@db:5432/warehouse_db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: